web:
  restart: always
  build: ./
  ports:
     - "8000:8000"
  command: /usr/local/bin/gunicorn challenge.wsgi:application -w 2 -b :8000
  volumes:
    - /usr/src/app
    - /usr/src/app/static

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
