# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('captain', 'Only team leaders'), ('student', 'All students')], max_length=50, verbose_name='User type')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('sentdate', models.DateTimeField(auto_now=True, verbose_name='Sent date')),
                ('status', models.CharField(choices=[('queue', 'In Queue'), ('sent', 'Sent')], default='queue', max_length=30, verbose_name='Email status')),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
                'db_table': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Captain')),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='School')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(verbose_name='At')),
                ('valid', models.BooleanField(verbose_name='Valid')),
                ('score', models.FloatField(verbose_name='Score')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Person')),
            ],
            options={
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('creation', models.DateField(verbose_name='Date of creation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.School')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Team'),
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Team'),
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Person'),
        ),
    ]
